// #define SPLIT_HAND_PIN GP4
// #define USB_VBUS_PIN GP14
// #define SERIAL_USART_FULL_DUPLEX
// #define SERIAL_USART_TX_PIN GP4
// #define SERIAL_USART_RX_PIN GP5
// #define SERIAL_USART_PIN_SWAP
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP4
#define I2C1_SCL_PIN GP5
